---
# Docker compose STACK file
version: "3"
services:
  # Scrape Service
  test_garage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "NIPKaart_${CITY}"
    networks:
      - backend
    restart: on-failure

# Networks
networks:
  backend:
    driver: overlay
