---
# Docker compose STACK file
version: "3"
services:
  # Scrape Amsterdam - Garage Service
  nipkaart_amsterdam_garages:
    image: nipkaart-garages-amsterdam:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5m

# Networks
networks:
  backend:
    driver: overlay
