---
# Docker compose STACK file
version: "3"
services:
  # Scrape Hamburg - Park and Ride Service
  nipkaart_hamburg_parkandride:
    image: nipkaart-parkandride-hamburg:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5m

# Networks
networks:
  backend:
    driver: overlay
