# Docker compose STACK file
version: "3"
services:
  # Scrape Hamburg Service
  nipkaart_hamburg:
    image: nipkaart-garages-hamburg:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3m

# Networks
networks:
  backend:
    driver: overlay
