# Docker compose STACK file
version: "3"
services:
  # Scrape Amsterdam Service
  nipkaart_amsterdam:
    image: nipkaart-garages-amsterdam:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

# Networks
networks:
  backend:
    driver: overlay
